### ISSUE TITLE
docker部署返回结果中文unicode编码了

### ISSUE THREAD

**Issue by xiaoliusec** [HG-ha/ICP_Query#1]
可以返回中文结果吗

**Comment by HG-ha** [comment]
> 可以返回中文结果吗

我不确定你的语言环境是否有合格的json工具，我认为输出unicode编码是正常的，如果你必须使输出的结果不进行编码的话，参考以下方法：

1. 执行以下命令，"CONTAINER ID" 是指正在运行的旧容器的ID
    docker exec -it "CONTAINER ID" sed -i 's/dumps(data)/dumps(data,ensure_ascii=False)/g' /usr/local/lib/python3.8/site-packages/aiohttp/web_response.py
2. copy当前运行的容器
    docker commit "CONTAINER ID" newymicp:latest
3. 关闭旧容器
    docker stop "CONTAINER ID"
5. 运行copy后的容器
    docker run -it -d -p 0.0.0.0:16181:16181 newymicp:latest
7. 删除旧容器，或者仍然保留它

**Comment by xiaoliusec** [comment]
好的，谢谢回复，我使用python请求接口将返回的unicodde字符转为中文解决了此问题
